name: Datadog Synthetics CI

on:
  push:
    branches:
      - main

jobs:
  synthetics-run:
    runs-on: ubuntu-latest
    if: ${{ secrets.DATADOG_API_KEY != '' && secrets.DATADOG_APP_KEY != '' }}
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

    - name: Run Datadog Synthetics tests
      # You can find the latest version here: https://github.com/DataDog/synthetics-ci-github-action/releases
      # We recommend that you pin the action to a specific commit SHA and update it regularly.
      uses: DataDog/synthetics-ci-github-action@87b505388a22005bb8013481e3f73a367b9a53eb # v1.4.0
      with:
        api_key: ${{ secrets.DATADOG_API_KEY }}
        app_key: ${{ secrets.DATADOG_APP_KEY }}
        test_search_query: 'tag:e2e-tests'
